<a href="https://colab.research.google.com/github/PR1YAM9/MachineLearning/blob/main/Linear_Regression_with_multiple_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
files.upload()

Saving data.csv to data (1).csv


{'data (1).csv': b'area,bedrooms,age,price\r\n2600,3,20,550000\r\n3000,4,15,565000\r\n3200,,18,610000\r\n3600,3,30,595000\r\n4000,5,8,760000\r\n'}

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
df = pd.read_csv('data.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
import math
valueBedrooms = math.floor(df['bedrooms'].median())
df['bedrooms'] = df['bedrooms'].fillna(valueBedrooms)
print(df['bedrooms'])

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64


In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression()

In [ ]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [ ]:
reg.intercept_

383724.9999999998

In [ ]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

Exercise


In [ ]:
from google.colab import files
files.upload()

Saving hiring.csv to hiring.csv


{'hiring.csv': b'\xef\xbb\xbfexperience,test_score(out of 10),interview_score(out of 10),salary($)\n,8,9,50000\n,8,6,45000\nfive,6,7,60000\ntwo,10,10,65000\nseven,9,6,70000\nthree,7,10,62000\nten,,7,72000\neleven,7,8,80000\n'}

In [ ]:
dfHiring = pd.read_csv('hiring.csv')
dfHiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
!pip install word2number
from word2number import w2n

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5566 sha256=3dbdcdccfe0a5402a5d55bf839954f73d5ee7e92fafd15b687776ce07e2bdc14
  Stored in directory: /root/.cache/pip/wheels/84/ff/26/d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number


In [ ]:
dfHiring['experience'] = dfHiring['experience'].apply(lambda x: w2n.word_to_num(x) if isinstance(x,str) else x)
dfHiring['experience'] = dfHiring['experience'].fillna(0)
dfHiring['experience']


0     0.0
1     0.0
2     5.0
3     2.0
4     7.0
5     3.0
6    10.0
7    11.0
Name: experience, dtype: float64

In [ ]:
valueNAN = math.floor(dfHiring['test_score(out of 10)'].median())
dfHiring['test_score(out of 10)'] = dfHiring['test_score(out of 10)'].fillna(valueNAN)
dfHiring['test_score(out of 10)']

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test_score(out of 10), dtype: float64

In [ ]:
dfHiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [ ]:
reghiring = linear_model.LinearRegression()
reghiring.fit(dfHiring[['experience','test_score(out of 10)','interview_score(out of 10)']],dfHiring['salary($)'])

LinearRegression()

In [ ]:
reghiring.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [ ]:
reghiring.intercept_

17737.263464337688

In [ ]:
reghiring.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])